# Generated by Django 5.1.5 on 2025-04-01 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_faq_answer_ru_faq_answer_uz_faq_question_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('working_days', models.CharField(choices=[('MON-FRI', 'Monday to Friday'), ('MON-SAT', 'Monday to Saturday'), ('CUSTOM', 'Custom Schedule')], default='MON-FRI', max_length=20)),
                ('working_hours', models.IntegerField(help_text='Working hours per day', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['fullname'],
            },
        ),
    ]
