# Generated by Django 5.1.5 on 2025-04-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='working_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_end',
            field=models.TimeField(default='17:00:00', help_text='Working hours end time (24-hour format)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours_start',
            field=models.TimeField(default='09:00:00', help_text='Working hours start time (24-hour format)'),
        ),
    ]
