# Generated by Django 5.1.5 on 2025-04-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_employee_working_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Name (Uzbek)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Name (Russian)')),
                ('code', models.CharField(help_text='Unique identifier for the region', max_length=10, unique=True, verbose_name='Region Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
    ]
