# Generated by Django 5.1.5 on 2025-04-01 04:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('father_name', models.CharField(max_length=100, verbose_name="Father's Name")),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron pochta')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('attachment', models.FileField(blank=True, max_length=5242880, null=True, upload_to='email_attachments/', validators=[django.core.validators.FileExtensionValidator(['txt', 'doc', 'rtf', 'xls', 'ppt', 'pdf', 'jpg', 'bmp', 'png', 'tiff', 'gif'])], verbose_name='Attachment')),
                ('message', models.TextField(max_length=5000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Murojaatlar',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
