# Generated by Django 5.1.5 on 2025-04-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_newstype_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_uz',
        ),
    ]
