# Generated by Django 5.2 on 2025-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='working_day',
            field=models.CharField(choices=[('MON', 'Dushanba'), ('TUE', 'Seshanba'), ('WED', 'Chorshanba'), ('THU', 'Payshanba'), ('FRI', 'Juma'), ('SAT', 'Shanba'), ('SUN', 'Yakshanba')], default='MON', max_length=3),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Rasm'),
        ),
    ]
