# Generated by Django 5.2 on 2025-04-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_employee_working_day_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('link', models.URLField(verbose_name='Link URL')),
                ('image', models.ImageField(upload_to='useful_links/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Foydali havola',
                'verbose_name_plural': 'Foydali havolalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
