# Generated by Django 5.2 on 2025-04-04 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('category', models.CharField(choices=[('preschool', "Maktabgacha ta'lim"), ('school', "Maktab ta'limi")], max_length=20, verbose_name='Category')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.city', verbose_name='City')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['-created_at'],
            },
        ),
    ]
