# Generated by Django 5.2 on 2025-04-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Takliflar statistikasi',
                'verbose_name_plural': 'Takliflar statistikasi',
                'ordering': ['name'],
            },
        ),
    ]
