# Generated by Django 5.2 on 2025-04-04 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_filescategory_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Yangiliklar kategoriyasi',
                'verbose_name_plural': 'Yangiliklar kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Shaxs turi',
                'verbose_name_plural': 'Shaxs turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('content_type', models.CharField(choices=[('photo', 'Rasm'), ('video', 'Video')], default='photo', max_length=10, verbose_name='Kontent turi')),
                ('image', models.ImageField(blank=True, help_text='Faqat rasmlar uchun', null=True, upload_to='gallery/photos/', verbose_name='Rasm')),
                ('video_url', models.URLField(blank=True, help_text='Faqat videolar uchun', null=True, verbose_name='Video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereya',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type'], name='backend_gal_content_8312be_idx')],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='backend.newscategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200, verbose_name='Lavozim')),
                ('biography', models.TextField(verbose_name='Biografiya')),
                ('start_hour', models.TimeField(verbose_name='Qabul vaqtining boshlanishi')),
                ('end_hour', models.TimeField(verbose_name='Qabul vaqtining tugashi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Pochta')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram sahifa')),
                ('work_experience', models.TextField(verbose_name='Mehnat faoliyati')),
                ('responsibilities', models.TextField(verbose_name='Vazifalari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='backend.persontype', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Shaxs',
                'verbose_name_plural': 'Shaxslar',
                'ordering': ['-created_at'],
            },
        ),
    ]
