# Generated by Django 5.2 on 2025-04-05 00:05

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_newscategory_persontype_gallery_news_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['fullname'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', '-created_at'], 'verbose_name': "Ko'p so'raladigan savollar", 'verbose_name_plural': "Ko'p so'raladigan savollar"},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fayl', 'verbose_name_plural': 'Fayllar'},
        ),
        migrations.AlterModelOptions(
            name='filescategory',
            options={'ordering': ['name'], 'verbose_name': 'Fayllar kategoriyasi', 'verbose_name_plural': 'Fayllar kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='newstype',
            options={'ordering': ['name'], 'verbose_name': 'Yangiliklar turi', 'verbose_name_plural': 'Yangiliklar turlari'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ['name'], 'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistika'},
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Tuman nomi'),
        ),
        migrations.AddField(
            model_name='city',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Tuman nomi'),
        ),
        migrations.AddField(
            model_name='emailform',
            name='message_ru',
            field=models.TextField(max_length=5000, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='emailform',
            name='message_uz',
            field=models.TextField(max_length=5000, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='emailform',
            name='subject_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='emailform',
            name='subject_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Mavzu'),
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname_ru',
            field=models.CharField(max_length=100, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='employee',
            name='fullname_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='files',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='files',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='files',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='files',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='filescategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='filescategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Galereya tavsifi'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Galereya tavsifi'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Galereya sarlavhasi'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Galereya sarlavhasi'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Yangilik tavsifi'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Yangilik tavsifi'),
        ),
        migrations.AddField(
            model_name='news',
            name='hashtag_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Xeshteg'),
        ),
        migrations.AddField(
            model_name='news',
            name='hashtag_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Xeshteg'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Yangilik sarlavhasi'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Yangilik sarlavhasi'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Yangiliklar kategoriyasi'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Yangiliklar kategoriyasi'),
        ),
        migrations.AddField(
            model_name='newstype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Yangilik turi'),
        ),
        migrations.AddField(
            model_name='newstype',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Yangilik turi'),
        ),
        migrations.AddField(
            model_name='offer',
            name='fullname_ru',
            field=models.CharField(max_length=100, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='offer',
            name='fullname_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="To'liq ism"),
        ),
        migrations.AddField(
            model_name='offer',
            name='message_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='offer',
            name='message_uz',
            field=models.TextField(max_length=1000, null=True, verbose_name='Xabar'),
        ),
        migrations.AddField(
            model_name='offerstats',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Takliflar statistikasi nomi'),
        ),
        migrations.AddField(
            model_name='offerstats',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Takliflar statistikasi nomi'),
        ),
        migrations.AddField(
            model_name='persons',
            name='biography_ru',
            field=models.TextField(null=True, verbose_name='Biografiya'),
        ),
        migrations.AddField(
            model_name='persons',
            name='biography_uz',
            field=models.TextField(null=True, verbose_name='Biografiya'),
        ),
        migrations.AddField(
            model_name='persons',
            name='position_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='persons',
            name='position_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='persons',
            name='responsibilities_ru',
            field=models.TextField(null=True, verbose_name='Vazifalar'),
        ),
        migrations.AddField(
            model_name='persons',
            name='responsibilities_uz',
            field=models.TextField(null=True, verbose_name='Vazifalar'),
        ),
        migrations.AddField(
            model_name='persons',
            name='work_experience_ru',
            field=models.TextField(null=True, verbose_name='Mehnat faoliyati'),
        ),
        migrations.AddField(
            model_name='persons',
            name='work_experience_uz',
            field=models.TextField(null=True, verbose_name='Mehnat faoliyati'),
        ),
        migrations.AddField(
            model_name='persontype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Shaxs turi nomi'),
        ),
        migrations.AddField(
            model_name='persontype',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Shaxs turi nomi'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Viloyat nomi'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Viloyat nomi'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Statistika nomi'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Statistika nomi'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='usefullink',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tuman nomi'),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='backend.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='attachment',
            field=models.FileField(blank=True, max_length=5242880, null=True, upload_to='email_attachments/', validators=[django.core.validators.FileExtensionValidator(['txt', 'doc', 'rtf', 'xls', 'ppt', 'pdf', 'jpg', 'bmp', 'png', 'tiff', 'gif'])], verbose_name='Ilova'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='Otasining ismi'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Lavozim'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_day',
            field=models.CharField(choices=[('MON', 'Dushanba'), ('TUE', 'Seshanba'), ('WED', 'Chorshanba'), ('THU', 'Payshanba'), ('FRI', 'Juma'), ('SAT', 'Shanba'), ('SUN', 'Yakshanba')], default='MON', max_length=3, verbose_name='Ish kuni'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_hours_end',
            field=models.TimeField(default='17:00:00', help_text='Ish vaqtining tugashi (24 soatlik format)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_hours_start',
            field=models.TimeField(default='09:00:00', help_text='Ish vaqtining boshlanishi (24 soatlik format)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_uz',
            field=models.TextField(null=True, verbose_name='Javob'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='files',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.filescategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='files',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='files',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='filescategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Galereya tavsifi'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, help_text='Faqat rasmlar uchun', null=True, upload_to='gallery/photos/', verbose_name='Galereya rasmi'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Galereya sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='backend.newscategory', verbose_name='Yangiliklar kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Yangilik tavsifi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='hashtag',
            field=models.CharField(max_length=100, verbose_name='Xeshteg'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Yangilik rasmi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.newstype', verbose_name='Yangilik turi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Yangilik sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Yangiliklar kategoriyasi'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Yangilik turi'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('preschool', "Maktabgacha ta'lim"), ('school', "Maktab ta'limi")], max_length=20, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.city', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='offer',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='offerstats',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Takliflar statistikasi nomi'),
        ),
        migrations.AlterField(
            model_name='offerstats',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Takliflar soni'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='responsibilities',
            field=models.TextField(verbose_name='Vazifalar'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram sahifasi'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='backend.persontype', verbose_name='Shaxs turi'),
        ),
        migrations.AlterField(
            model_name='persontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Shaxs turi nomi'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(help_text='Viloyat uchun noyob identifikator', max_length=10, unique=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Viloyat nomi'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Statistika nomi'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='link',
            field=models.URLField(verbose_name='Havola'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
    ]
