# Generated by Django 5.2 on 2025-04-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_employee_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
    ]
