# Generated by Django 5.2 on 2025-04-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Ovozlar soni'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.CharField(choices=[('excellent', "Zo'r"), ('good', 'Yaxshi'), ('satisfactory', 'Qoniqarli'), ('unsatisfactory', 'Qoniqarsiz')], max_length=20, verbose_name='Ovoz berish varianti'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
