# Generated by Django 5.2 on 2025-04-05 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_vote_count_alter_vote_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
        migrations.CreateModel(
            name='DistrictLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.city', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'District Leader',
                'verbose_name_plural': 'District Leaders',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name="To'liq ism")),
                ('working_hours_start', models.TimeField(default='09:00:00', help_text='Ish vaqtining boshlanishi (24 soatlik format)')),
                ('working_hours_end', models.TimeField(default='17:00:00', help_text='Ish vaqtining tugashi (24 soatlik format)')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Viloyat rahbari',
                'verbose_name_plural': 'Viloyat rahbarlari',
                'ordering': ['fullname'],
            },
        ),
    ]
