# Generated by Django 5.2 on 2025-04-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_districtleader_options_districtleader_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='Rasm'),
        ),
    ]
