# Generated by Django 5.2 on 2025-04-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opendata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Opendata',
                'verbose_name_plural': 'Opendata',
                'ordering': ['-created_at'],
            },
        ),
    ]
