# Generated by Django 5.2 on 2025-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_opendata'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendata',
            name='created_at_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='opendata',
            name='created_at_uz',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='opendata',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opendata',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
