# Generated by Django 5.2 on 2025-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_opendata_created_at_ru_opendata_created_at_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='description',
        ),
        migrations.RemoveField(
            model_name='files',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='files',
            name='description_uz',
        ),
        migrations.AlterField(
            model_name='files',
            name='title',
            field=models.CharField(verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='files',
            name='title_uz',
            field=models.CharField(null=True, verbose_name='Sarlavha'),
        ),
    ]
