# Generated by Django 5.2 on 2025-04-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_remove_files_description_remove_files_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='url',
            field=models.FileField(upload_to='files/', verbose_name='URL'),
        ),
    ]
